# Generated by Django 4.1.7 on 2024-07-11 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('banner', models.CharField(max_length=255)),
                ('rating', models.FloatField(max_length=255)),
            ],
        ),
    ]
